version: 2.1

jobs:
  build_node:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install node deps
          working_directory: zincbase/web/frontend/
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: /root/project/zincbase/web/frontend/
          paths:
            - bundle.js
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: /frontend
      - run:
          name: Install deps
          command: |
            python3 -m pip install --upgrade pip setuptools --ignore-installed
            python3 -m pip install -r requirements.txt
      - run:
          name: Build and install package
          command: |
            python3 setup.py build
            python3 setup.py sdist bdist_wheel
            python3 setup.py install
      - run:
          name: Run Tests
          command: |
            python3 -m doctest zincbase/zincbase.py
            python3 test/test_attr.py
            python3 test/test_main.py
            python3 test/test_lists.py
            python3 test/test_graph.py
            python3 test/test_nn_basic.py
            python3 test/test_nn.py
            python3 test/test_neg_examples.py
            python3 test/test_truthiness.py
            python3 test/test_propagation.py
  build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Preliminary installation
          command: |
            python3 -m pip install -r requirements.txt
            python3 -m pip install twine
      - run:
          name: Build package
          command: python setup.py sdist bdist_wheel --universal
      - run:
          name: Upload to pypi
          command: twine upload dist/* || true
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_node:
          name: build_node_first
      - test:
          requires:
            - build_node_first
          name: test_first
      - build:
          requires:
            - test_first
          filters:
            branches:
              only:
                - master

